name: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_ENVIRONMENT: ${{ inputs.environment || 'dev' }}

    environment: ${{ inputs.environment || 'dev' }}
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.10.5
          
      - name: Print environment variable
        run: 'echo "MY_VAR is: ${{ vars.MSG }}"'
        
      - name: Init
        working-directory: terraform/environments/${{ env.TF_ENVIRONMENT }}
        run: terraform init
      - name: Plan (review in logs)
        working-directory: terraform/environments/${{ env.TF_ENVIRONMENT }}
        run: terraform plan

  apply:
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ inputs.environment || 'dev' }}
    env:
      TF_ENVIRONMENT: ${{ inputs.environment || 'dev' }}
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.10.5
      - name: Init
        working-directory: terraform/environments/${{ env.TF_ENVIRONMENT }}
        run: terraform init
      - name: Apply (approval already done in GitHub)
        working-directory: terraform/environments/${{ env.TF_ENVIRONMENT }}
        run: terraform apply -auto-approve
   
